name: Frontend Check

on:
  pull_request:
    branches: [ develop ]
    
defaults:
  run:
    working-directory: ./

jobs:
  Frontend-Build-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Use Node.js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '16.x'
      - run: yarn install
      - run: CI=false yarn build
        env:
            NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
            GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}
